modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL = "https://github.com/${mod_authors}/${project.name}/issues/"
license="MIT"

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/warium-additions"
    logoFile = "icon.png"
    credits="${credits}"
	authors="${mod_authors}" 
	description='''${mod_description}'''
    mixins = "${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true 
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="crusty_chunks"
    mandatory=true 
    versionRange="[${warium_version},)"
    ordering="AFTER"
    side="BOTH"
	
[[dependencies.${mod_id}]]
    modId="ponder"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="CLIENT"
	
[[dependencies.${mod_id}]]
    modId="create"
    mandatory=false
    versionRange="[${create_version},)"
    ordering="AFTER"
    side="BOTH"
	
[[dependencies.${mod_id}]]
    modId="warium_ponder"
    mandatory=false
    versionRange="[INCOMPATIBLE]"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.${mod_id}]]
    modId="warium_create"
    mandatory=false
    versionRange="[INCOMPATIBLE]"
    ordering="NONE"
    side="BOTH"